### ISSUE TITLE
galaxy workflow importing link

### ISSUE THREAD

**Issue by swbioinf** [AustralianBioCommons/guide-template#1]
Minor suggestion - could there be an example (or link) of how to link a workflowhub workflow to import? 

e.g. these links: https://usegalaxy.org.au/workflows/trs_import?trs_server=workflowhub.eu&trs_id=403&trs_version=2

I can't find a link to a page or snippet that describes these, but they're pretty intuitive, so something like below could be enough?

```
To provide a link to the user to import a workflow with one click, create a URL with the following format
https://usegalaxy.org.au/workflows/trs_import?trs_server=workflowhub.eu&trs_id=403&trs_version=2

Where 403 is the workflowhub id, which  may be found in workflowhub URL: https://workflowhub.eu/workflows/403
```

**Comment by supernord** [comment]
thanks for the suggestion @swbioinf
I've added some content to this page: https://australianbiocommons.github.io/how-to-guide-template/improve_content
