### ISSUE TITLE
Allowing categorisation of files under pages into sub-directories

### ISSUE THREAD

**Issue by ziadbkh** [AustralianBioCommons/guide-template#3]
Maybe it is useful to have subdirectories under pages directories and then the user can redirect to these pages as base_url/subdirectory/page_name. It does not work like this now, but it works with the full link base_url/pages/subdirectory/page_name

**Comment by supernord** [comment]
hi @ziadbkh 
I think this is already possible. @bedroesb, please let me know if the below isn't correct 😄 
The [config file](https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/blob/main/_config.yml#LL32C1-L40C20) and [pages directory](https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/tree/main/pages) for the [ELIXIR toolkit theme example)(https://elixir-belgium.github.io/elixir-toolkit-theme/):
- uses sub-directories within the `pages` directory
- refers to its `pages` directory within the `config.yml` file
- includes this in the `main.yml` sidebar file without referring to the directory structure, and
- "pages" does not appear in the urls, for example see https://elixir-belgium.github.io/elixir-toolkit-theme/getting_started

as long as this matches to our implementation of the theme, then it should work?

what about if we remove the `pages/directory` bit for each of the pages in the `main.yml`? here: https://github.com/AustralianBioCommons/tower/blob/main/_data/sidebars/main.yml
